mutation AddItem($data: ItemCreateInput!) {
  createOneItem(data: $data) {
    id
    owner {
      email
    }
    description
    model
    spark
    count
    monetaryValue
    link
    notes
    image
  }
}

query getUserCategories($ownerId: Int) {
  categoriesByUser(ownerId: $ownerId) {
    id
    title
  }
}

query getUserLocations($ownerId: Int) {
  locationsByUser(ownerId: $ownerId) {
    id
    title
  }
}

query getUserTags($ownerId: Int) {
  tagsByUser(ownerId: $ownerId) {
    id
    title
  }
}

mutation UpdateItem($data: ItemUpdateInput!, $where: ItemWhereUniqueInput!) {
  updateOneItem(data: $data, where: $where) {
    id
    owner {
      email
    }
    description
    model
    spark
    count
    monetaryValue
    link
    notes
    image
    categories {
      id
      title
      ownerId
    }
    locations {
      id
      title
      ownerId
    }
    tags {
      id
      title
      ownerId
    }
  }
}

mutation AddOrUpdateItem($where: ItemWhereUniqueInput!, $create: ItemCreateInput!, $update: ItemUpdateInput!) {
  upsertOneItem(where: $where, create: $create, update: $update) {
    id
    owner {
      email
    }
    description
    model
    spark
    count
    monetaryValue
    link
    notes
    image
    categories {
      id
      title
      ownerId
    }
    locations {
      id
      title
      ownerId
    }
    tags {
      id
      title
      ownerId
    }
  }
}
