query getItem($where: ItemWhereUniqueInput!) {
  item(where: $where) {
    id
    owner {
      email
    }
    ownerId
    description
    model
    categories {
      id
      title
    }
    locations {
      id
      title
    }
    spark
    count
    monetaryValue
    link
    notes
    tags {
      id
      title
    }
    image
  }
}
